version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-comp
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gamedb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-comp
    ports:
      - "6379:6379"

  backend:
    image: shivamarora96/catcardgame-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_CONN_STRING: "postgres://user:password@postgres:5432/gamedb?sslmode=disable"
      REDIS_ADDR: "redis:6379"

volumes:
  postgres-data:
