version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-comp
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gamedb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis-comp
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  frontend:
    image: shivamarora96/catcardgame:latest
    container_name: frontend
    ports:
      - "5173:5173" # Map to port 5173 for public access
    networks:
      - mynetwork
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  backend:
    image: shivamarora96/catcardgame-backend:latest
    container_name: backend
    ports:
      - "8080:8080" # Expose to public access
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_CONN_STRING: "postgres://user:password@postgres:5432/gamedb?sslmode=disable"
      REDIS_ADDR: "redis:6379"
    networks:
      - mynetwork

volumes:
  postgres-data:

networks:
  mynetwork:
    driver: bridge
